In [54]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [55]:
df = sns.load_dataset('iris')

In [56]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [57]:
df['species'].unique()
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [58]:
from sklearn.model_selection import train_test_split

X = df.drop('species',axis=1)
y = df['species']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [59]:
X_train.head()

     sepal_length  sepal_width  petal_length  petal_width
96            5.7          2.9           4.2          1.3
105           7.6          3.0           6.6          2.1
66            5.6          3.0           4.5          1.5
0             5.1          3.5           1.4          0.2
122           7.7          2.8           6.7          2.0

In [60]:
from sklearn.neighbors import KNeighborsClassifier

model_KNN = KNeighborsClassifier(n_neighbors=3)

In [61]:
model_KNN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [62]:
model_KNN.score(X_test,y_test)

0.98

In [63]:
#By changing the parameters n_neighbors = [3,5,7,9..] the score changes like 0.98,1.0

In [64]:
from sklearn.svm import SVC

model_svm = SVC(C=30,kernel='linear',gamma='auto')
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [65]:
model_svm.score(X_test,y_test)

0.98

In [66]:
#By changing the parameters kernel = ['rbf','linear'] and C=1,10,20,30 the score changes like 0.98,1.0

In [67]:
from sklearn.model_selection import GridSearchCV

classifier1 = GridSearchCV((model_svm),{
    'C' : [1,10,20,30,40],
    'kernel' : ['rbf','linear'],
    'gamma' :['auto','scale']
},cv=5,return_train_score=False)

classifier1.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30, 40], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']})

In [68]:
classifier1.cv_results_

{'mean_fit_time': array([0.0031733 , 0.00228968, 0.00276098, 0.00285192, 0.00332208,
        0.00270123, 0.00263505, 0.00264282, 0.00310493, 0.00281973,
        0.00283155, 0.00247784, 0.00270295, 0.00260725, 0.00313187,
        0.00274081, 0.00285969, 0.00298376, 0.00243235, 0.00260735]),
 'std_fit_time': array([6.96043144e-04, 2.28926515e-04, 3.24638449e-04, 3.30104601e-04,
        7.12940481e-04, 2.69939128e-04, 7.76432936e-05, 1.47794398e-04,
        3.57408456e-04, 3.35770173e-04, 4.37000863e-04, 1.89316507e-04,
        3.11089308e-04, 3.06799214e-04, 9.62104457e-04, 6.33671183e-04,
        3.58544656e-04, 5.30993394e-04, 3.31118929e-04, 3.69378297e-04]),
 'mean_score_time': array([0.00256376, 0.00176258, 0.00203533, 0.00199723, 0.00228214,
        0.00217171, 0.00197263, 0.00214615, 0.00217853, 0.00214438,
        0.00187435, 0.00191574, 0.00187497, 0.00195994, 0.00193472,
        0.00213046, 0.00192609, 0.00223885, 0.00182543, 0.00198679]),
 'std_score_time': array([4.68506653e-04, 6.63056428e-05, 2.65760920e-04, 1.19475354e-04,
        2.27832126e-04, 4.49978202e-04, 3.31785474e-05, 2.48953233e-04,
        1.14798246e-04, 1.65852669e-04, 1.77125115e-04, 1.79410664e-04,
        1.29809263e-04, 2.10025123e-04, 1.38919810e-04, 4.90362590e-04,
        1.18938960e-04, 5.20464790e-04, 2.38521582e-04, 2.96043204e-04]),
 'param_C': masked_array(data=[1, 1, 1, 1, 10, 10, 10, 10, 20, 20, 20, 20, 30, 30, 30,
                    30, 40, 40, 40, 40],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_gamma': masked_array(data=['auto', 'auto', 'scale', 'scale', 'auto', 'auto',
                    'scale', 'scale', 'auto', 'auto', 'scale', 'scale',
                    'auto', 'auto', 'scale', 'scale', 'auto', 'auto',
                    'scale', 'scale'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 40, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 40, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 40, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 40, 'gamma': 'scale', 'kernel': 'linear'}],
 'split0_test_score': array([0.95, 1.  , 1.  , 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95,
        0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.85, 0.9 , 0.8 , 0.85, 0.9 , 0.85, 0.8 , 0.85, 0.9 ,
        0.85, 0.8 , 0.85, 0.85, 0.85, 0.8 , 0.85, 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9,
        0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  ,
        0.95, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ]),
 'split4_test_score': array([0.95, 0.95, 0.9 , 0.95, 1.  , 0.95, 0.95, 0.95, 0.95, 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.94, 0.95, 0.93, 0.95, 0.93, 0.93, 0.94, 0.93, 0.92, 0.93, 0.95,
        0.93, 0.93, 0.94, 0.94, 0.94, 0.93, 0.94, 0.93, 0.94]),
 'std_test_score': array([0.03741657, 0.04472136, 0.06      , 0.04472136, 0.07483315,
        0.0509902 , 0.03741657, 0.0509902 , 0.0678233 , 0.0509902 ,
        0.04472136, 0.0509902 , 0.07483315, 0.05830952, 0.05830952,
        0.05830952, 0.07483315, 0.05830952, 0.07483315, 0.05830952]),
 'rank_test_score': array([ 4,  1, 11,  1, 11, 16,  4, 16, 20, 16,  1, 16, 11,  6,  6,  6, 11,
         6, 11,  6], dtype=int32)}

In [69]:
result1 = pd.DataFrame(classifier1.cv_results_)
result1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003173,0.000696,0.002564,0.000469,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,4
1,0.002290,0.000229,0.001763,0.000066,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
2,0.002761,0.000325,0.002035,0.000266,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",1.00,0.85,0.9,1.00,0.90,0.93,0.060000,11
3,0.002852,0.000330,0.001997,0.000119,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
4,0.003322,0.000713,0.002282,0.000228,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,11
5,0.002701,0.000270,0.002172,0.000450,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,16
6,0.002635,0.000078,0.001973,0.000033,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,4
7,0.002643,0.000148,0.002146,0.000249,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,16
8,0.003105,0.000357,0.002179,0.000115,20,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,20
9,0.002820,0.000336,0.002144,0.000166,20,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,16
10,0.002832,0.000437,0.001874,0.000177,20,scale,rbf,"{'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,1.00,0.95,0.044721,1
11,0.002478,0.000189,0.001916,0.000179,20,scale,linear,"{'C': 20, 'gamma': 'scale', 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,16
12,0.002703,0.000311,0.001875,0.000130,30,auto,rbf,"{'C': 30, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,11
13,0.002607,0.000307,0.001960,0.000210,30,auto,linear,"{'C': 30, 'gamma': 'auto', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6
14,0.003132,0.000962,0.001935,0.000139,30,scale,rbf,"{'C': 30, 'gamma': 'scale', 'kernel': 'rbf'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6
15,0.002741,0.000634,0.002130,0.000490,30,scale,linear,"{'C': 30, 'gamma': 'scale', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6
16,0.002860,0.000359,0.001926,0.000119,40,auto,rbf,"{'C': 40, 'gamma': 'auto', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,11
17,0.002984,0.000531,0.002239,0.000520,40,auto,linear,"{'C': 40, 'gamma': 'auto', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6
18,0.002432,0.000331,0.001825,0.000239,40,scale,rbf,"{'C': 40, 'gamma': 'scale', 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,11
19,0.002607,0.000369,0.001987,0.000296,40,scale,linear,"{'C': 40, 'gamma': 'scale', 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,6

In [70]:
result1[['param_C','param_gamma','param_kernel','mean_test_score']]

    param_C param_gamma param_kernel  mean_test_score
0         1        auto          rbf             0.94
1         1        auto       linear             0.95
2         1       scale          rbf             0.93
3         1       scale       linear             0.95
4        10        auto          rbf             0.93
5        10        auto       linear             0.93
6        10       scale          rbf             0.94
7        10       scale       linear             0.93
8        20        auto          rbf             0.92
9        20        auto       linear             0.93
10       20       scale          rbf             0.95
11       20       scale       linear             0.93
12       30        auto          rbf             0.93
13       30        auto       linear             0.94
14       30       scale          rbf             0.94
15       30       scale       linear             0.94
16       40        auto          rbf             0.93
17       40        auto       linear             0.94
18       40       scale          rbf             0.93
19       40       scale       linear             0.94

In [71]:
from sklearn.model_selection import GridSearchCV

classifier2 = GridSearchCV((model_KNN),{
    'n_neighbors' : [3,5,7,9]
},cv=5,return_train_score=False)

classifier2.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3),
             param_grid={'n_neighbors': [3, 5, 7, 9]})

In [72]:
classifier2.cv_results_

{'mean_fit_time': array([0.00370917, 0.00333686, 0.0024642 , 0.00261765]),
 'std_fit_time': array([0.00111704, 0.00068221, 0.00033813, 0.00059791]),
 'mean_score_time': array([0.00414362, 0.004599  , 0.00321093, 0.00335846]),
 'std_score_time': array([0.0007921 , 0.00142514, 0.00016184, 0.00035383]),
 'param_n_neighbors': masked_array(data=[3, 5, 7, 9],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'n_neighbors': 3},
  {'n_neighbors': 5},
  {'n_neighbors': 7},
  {'n_neighbors': 9}],
 'split0_test_score': array([0.95, 0.9 , 0.9 , 0.9 ]),
 'split1_test_score': array([0.85, 0.9 , 0.9 , 0.9 ]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1., 1., 1., 1.]),
 'split4_test_score': array([0.95, 0.95, 0.95, 0.95]),
 'mean_test_score': array([0.93, 0.93, 0.93, 0.93]),
 'std_test_score': array([0.0509902, 0.04     , 0.04     , 0.04     ]),
 'rank_test_score': array([4, 1, 1, 1], dtype=int32)}

In [73]:
result2 = pd.DataFrame(classifier2.cv_results_)
result2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003709,0.001117,0.004144,0.000792,3,{'n_neighbors': 3},0.95,0.85,0.9,1.0,0.95,0.93,0.05099,4
1,0.003337,0.000682,0.004599,0.001425,5,{'n_neighbors': 5},0.90,0.90,0.9,1.0,0.95,0.93,0.04000,1
2,0.002464,0.000338,0.003211,0.000162,7,{'n_neighbors': 7},0.90,0.90,0.9,1.0,0.95,0.93,0.04000,1
3,0.002618,0.000598,0.003358,0.000354,9,{'n_neighbors': 9},0.90,0.90,0.9,1.0,0.95,0.93,0.04000,1

In [74]:
result2[['param_n_neighbors','mean_test_score']]

   param_n_neighbors  mean_test_score
0                  3             0.93
1                  5             0.93
2                  7             0.93
3                  9             0.93

In [75]:
from sklearn.model_selection import RandomizedSearchCV

classifier3 = RandomizedSearchCV((model_svm),{
    'C': [1,10,20,30,40],
    'kernel' : ['rbf','linear'],
    'gamma':['auto','scale']
},n_iter=4,cv=5,return_train_score=False)

In [76]:
classifier3.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto', kernel='linear'),
                   n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30, 40],
                                        'gamma': ['auto', 'scale'],
                                        'kernel': ['rbf', 'linear']})

In [77]:
df_random_svm = pd.DataFrame(classifier3.cv_results_)
df_random_svm

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_gamma,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003182,0.000329,0.002797,0.000690,linear,auto,30,"{'kernel': 'linear', 'gamma': 'auto', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4
1,0.002581,0.000255,0.001991,0.000321,rbf,scale,40,"{'kernel': 'rbf', 'gamma': 'scale', 'C': 40}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,3
2,0.002518,0.000108,0.001879,0.000154,rbf,auto,10,"{'kernel': 'rbf', 'gamma': 'auto', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002797,0.000158,0.002301,0.000427,rbf,scale,10,"{'kernel': 'rbf', 'gamma': 'scale', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [81]:
classifier4 = RandomizedSearchCV((model_KNN),{
    'n_neighbors':[3,5,7,9]
},n_iter=4,cv=5,return_train_score=False)

In [84]:
classifier4.fit(X,y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3),
                   n_iter=4, param_distributions={'n_neighbors': [3, 5, 7, 9]})

In [85]:
df_random_KNN = pd.DataFrame(classifier4.cv_results_)
df_random_KNN

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004388,0.000391,0.006597,0.000833,3,{'n_neighbors': 3},0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,4
1,0.005769,0.002045,0.006360,0.001130,5,{'n_neighbors': 5},0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,2
2,0.005070,0.001037,0.007407,0.002311,7,{'n_neighbors': 7},0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.005417,0.000989,0.006188,0.000530,9,{'n_neighbors': 9},0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,2